import MyAppBar from "@/components/MyAppBar";
import { getActiveTheme, selectTheme } from "@/redux/reducers/themeReducer";
import { ThemeProvider } from "@emotion/react";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { darkTheme, lightTheme } from "@/styles/mui/theme";
import { Box, Container, CssBaseline } from "@mui/material";

export default function Blog() {
  const dispatch = useDispatch();

  const currentTheme = useSelector(selectTheme).activeTheme;

  useEffect(() => {
    dispatch(getActiveTheme()); // To get the theme from the cookie
  });

  return (
    <>
      <ThemeProvider theme={currentTheme === "dark" ? darkTheme : lightTheme}>
        <CssBaseline />
        <Head>
          <title>Blog Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container>
          <Box height="2000px" />
        </Container>
      </ThemeProvider>
    </>
  );
}
