import Head from "next/head";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

import {
  Box,
  Button,
  Container,
  Grid,
  Skeleton,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { CustomCard, CustomDialog } from "@/styles/mui/customComponents";
import { fetchMovies, selectMovies } from "@/redux/reducers/movieReducer";

import AddIcon from "@mui/icons-material/Add";
import {
  addMovie,
  deleteMovie,
  updateMovie,
} from "@/redux/actions/movieAction";
import { selectUserAuth } from "@/redux/reducers/authReducer";

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(fetchMovies());
  }, []);

  const movies = useSelector(selectMovies);

  const { userAuthData } = useSelector(selectUserAuth);
  const isAuthenticated = !!userAuthData;

  // add/update movie dialog
  const [openMovieDialog, setOpenMovieDialog] = useState(false);
  const [currentMovie, setCurrentMovie] = useState({
    name: "",
    img: "",
    desc: "",
  });

  const [isEdit, setIsEdit] = useState(false);

  const handleOpenMovieDialog = (
    movie = { name: "", img: "", desc: "" },
    isEdit = false,
  ) => {
    setCurrentMovie(movie);
    setIsEdit(isEdit);
    setOpenMovieDialog(true);
  };
  const handleCloseMovieDialog = () => {
    setOpenMovieDialog(false);
    setCurrentMovie({ name: "", img: "", desc: "" });
  };

  const handleMovieDataChange = (e) => {
    setCurrentMovie({ ...currentMovie, [e.target.name]: e.target.value });
  };

  const handleSubmit = async () => {
    if (isEdit) {
      await updateMovie({ ...currentMovie, id: currentMovie._id });
    } else {
      if (
        currentMovie.name === "" ||
        currentMovie.img === "" ||
        currentMovie.desc === ""
      ) {
        return;
      }
      await addMovie(currentMovie);
    }
    dispatch(fetchMovies());
    handleCloseMovieDialog();
  };

  // delete movie dialog
  const [openDeleteDialog, setOpenDelete] = useState(false);
  const [deleteMovieId, setDeleteMovieId] = useState(null);

  const handleDelete = async () => {
    await deleteMovie(deleteMovieId);
    dispatch(fetchMovies());
    setOpenDelete(false);
    setDeleteMovieId(null);
  };

  return (
    <>
      <Head>
        <title>My Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box height="30px" />
      <Container maxWidth="lg">
        {isAuthenticated && (
          <Box display="flex" justifyContent="flex-end" alignItems="center">
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => handleOpenMovieDialog()}
            >
              Add Movie
            </Button>
          </Box>
        )}
        <Box height="20px" />
        {/* <Button onClick={() => fetchMovies()}>Get Movies</Button> */}
        <Box height="20px" />
        <Grid container spacing={2} direction="row" justifyContent="center">
          {movies.loading === "loaded" ? (
            movies.movies.map((movie) => (
              <Grid size={{ lg: 4, md: 4, sm: 6, xs: 12 }}>
                <CustomCard
                  name={movie.name}
                  image={movie.img}
                  description={movie.desc}
                  isAuthenticated={isAuthenticated}
                  onEdit={() => handleOpenMovieDialog(movie, true)}
                  onDelete={() => {
                    setDeleteMovieId(movie._id);
                    setOpenDelete(true);
                  }}
                />
              </Grid>
            ))
          ) : movies.loading === "loading" ? (
            <Grid container spacing={2} direction="row" justifyContent="center">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((item) => (
                <Grid size={{ lg: 4, md: 4, sm: 6, xs: 12 }}>
                  <Stack spacing={1}>
                    <Skeleton
                      variant="rectangular"
                      width={345}
                      height={320}
                      sx={{ borderRadius: "24px" }}
                    />
                  </Stack>
                </Grid>
              ))}
            </Grid>
          ) : (
            <Typography>No Data Found</Typography>
          )}
        </Grid>
      </Container>

      <CustomDialog
        open={openMovieDialog}
        title={isEdit ? "Edit Movie" : "Add Movie"}
        actions={
          <>
            <Button onClick={handleCloseMovieDialog}>Close</Button>
            <Button variant="contained" onClick={handleSubmit}>
              Save
            </Button>
          </>
        }
      >
        <Stack spacing={2}>
          <TextField
            name="name"
            label="Movie Name"
            fullWidth
            value={currentMovie?.name}
            onChange={handleMovieDataChange}
          />
          <TextField
            name="img"
            label="Movie Image URL"
            fullWidth
            value={currentMovie?.img}
            onChange={handleMovieDataChange}
          />
          <TextField
            name="desc"
            label="Movie Description"
            fullWidth
            multiline
            rows={4}
            value={currentMovie?.desc}
            onChange={handleMovieDataChange}
          />
        </Stack>
      </CustomDialog>

      <CustomDialog
        open={openDeleteDialog}
        title={"Confirm Delete"}
        actions={
          <>
            <Button onClick={() => setOpenDelete(false)}>Cancel</Button>
            <Button
              variant="contained"
              color="error"
              onClick={() => handleDelete()}
            >
              Delete
            </Button>
          </>
        }
      >
        <Typography>Are you sure you want to delete this movie?</Typography>
      </CustomDialog>
    </>
  );
}
