import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import axios from "axios"; // npm i axios
import { useDispatch, useSelector } from "react-redux";
import { getActiveTheme, selectTheme } from "@/redux/reducers/themeReducer";

import MyAppBar from "@/components/MyAppBar";
import {
  Box,
  Button,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Container,
  CssBaseline,
  Grid,
  Skeleton,
  Stack,
  ThemeProvider,
  Typography,
} from "@mui/material";
import { CustomCard } from "@/styles/mui/customComponents";
import { darkTheme, lightTheme } from "@/styles/mui/theme";
import { fetchMovies, selectMovies } from "@/redux/reducers/movieReducer";

export default function Home() {
  const dispatch = useDispatch();

  const currentTheme = useSelector(selectTheme).activeTheme;

  useEffect(() => {
    dispatch(getActiveTheme()); // To get the theme from the cookie
    dispatch(fetchMovies());
    // fetchMovies();
  }, []);

  const movies = useSelector(selectMovies);

  // STATE HOOK
  // const [showMovies, setShowMovies] = useState(true);
  // const [movies, setMovies] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  // Fetch Movies
  // const fetchMovies = async () => {
  //   try {
  //     setIsLoading(true);
  //     const response = await axios.get("/api/v1/get/movies");
  //     console.log("response: ", response.data);

  //     setMovies(response.data);
  //     setIsLoading(false);
  //   } catch (error) {
  //     console.error("ERROR FETCHING MOVIES: ", error);
  //     throw { error: error.message };
  //   } finally {
  //     console.log("finally");
  //   }
  // };

  return (
    <>
      <ThemeProvider theme={currentTheme === "dark" ? darkTheme : lightTheme}>
        <CssBaseline />
        <Head>
          <title>My Movies</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MyAppBar />
        <Box height="60px" />
        <Container maxWidth="lg">
          {/* <Button onClick={() => setShowMovies(!showMovies)}>
            Show/Hide Movies
          </Button> */}
          <Box height="20px" />
          {/* <Button onClick={() => fetchMovies()}>Get Movies</Button> */}
          <Box height="20px" />
          <Grid container spacing={2} direction="row" justifyContent="center">
            {movies.loading === "loaded" ? (
              movies.movies.map((movie) => (
                <Grid size={{ lg: 4, md: 4, sm: 6, xs: 12 }}>
                  <CustomCard
                    name={movie.name}
                    image={movie.img}
                    description={movie.desc}
                  />
                </Grid>
              ))
            ) : isLoading ? (
              <Grid
                container
                spacing={2}
                direction="row"
                justifyContent="center"
              >
                {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((item) => (
                  <Grid size={{ xl: 4, md: 4, xs: 12 }}>
                    <Stack spacing={1}>
                      <Skeleton
                        variant="rectangular"
                        width={345}
                        height={320}
                        sx={{ borderRadius: "24px" }}
                      />
                    </Stack>
                  </Grid>
                ))}
              </Grid>
            ) : (
              <Typography>No Data Found</Typography>
            )}
          </Grid>
        </Container>
      </ThemeProvider>
    </>
  );
}
